substitutions:
  _REGION: asia-southeast1
  _SERVICE_NAME: sekyu
  _MIGRATE_JOB_NAME: sekyu-migrate
  _OPTIMIZE_JOB_NAME: sekyu-optimize-clear
  _REPOSITORY: sekyu-repo
  _CLOUDSQL_INSTANCE: sekyu-500407:asia-southeast1:sekyu-db
  _IMAGE: asia-southeast1-docker.pkg.dev/$PROJECT_ID/sekyu-repo/sekyu:$SHORT_SHA

steps:
  - name: gcr.io/cloud-builders/docker
    args: ['build', '-t', '${_IMAGE}', '.']

  - name: gcr.io/cloud-builders/docker
    args: ['push', '${_IMAGE}']

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - ${_SERVICE_NAME}
      - --image=${_IMAGE}
      - --region=${_REGION}
      - --platform=managed
      - --allow-unauthenticated
      - --port=8080
      - --add-cloudsql-instances=${_CLOUDSQL_INSTANCE}
      - --set-env-vars=APP_ENV=production,DB_CONNECTION=mysql,DB_HOST=127.0.0.1,DB_SOCKET=/cloudsql/${_CLOUDSQL_INSTANCE},DB_PORT=3306,DB_DATABASE=sekyu,DB_USERNAME=sekyu,CACHE_STORE=file
      - --set-secrets=DB_PASSWORD=sekyu-db-password:latest

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - jobs
      - deploy
      - ${_MIGRATE_JOB_NAME}
      - --image=${_IMAGE}
      - --region=${_REGION}
      - --set-cloudsql-instances=${_CLOUDSQL_INSTANCE}
      - --set-env-vars=APP_ENV=production,DB_CONNECTION=mysql,DB_HOST=127.0.0.1,DB_SOCKET=/cloudsql/${_CLOUDSQL_INSTANCE},DB_PORT=3306,DB_DATABASE=sekyu,DB_USERNAME=sekyu,CACHE_STORE=file
      - --set-secrets=DB_PASSWORD=sekyu-db-password:latest
      - --command=php
      - --args=artisan,migrate,--force

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - jobs
      - execute
      - ${_MIGRATE_JOB_NAME}
      - --region=${_REGION}
      - --wait

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - jobs
      - deploy
      - ${_OPTIMIZE_JOB_NAME}
      - --image=${_IMAGE}
      - --region=${_REGION}
      - --set-cloudsql-instances=${_CLOUDSQL_INSTANCE}
      - --set-env-vars=APP_ENV=production,DB_CONNECTION=mysql,DB_HOST=127.0.0.1,DB_SOCKET=/cloudsql/${_CLOUDSQL_INSTANCE},DB_PORT=3306,DB_DATABASE=sekyu,DB_USERNAME=sekyu,CACHE_STORE=file
      - --set-secrets=DB_PASSWORD=sekyu-db-password:latest
      - --command=php
      - --args=artisan,optimize:clear

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - jobs
      - execute
      - ${_OPTIMIZE_JOB_NAME}
      - --region=${_REGION}
      - --wait

images:
  - ${_IMAGE}
